version: "3.3"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - "drizzle-migrations-db:/var/lib/postgresql/data"

volumes:
  drizzle-migrations-db:
